### PR TITLE
Example cnf

### PR DESCRIPTION
**Pull request by isaacdorfman**

### CODE REVIEW

**Comment by HamadiSE** [comment]
what's the purpose of this merge ? is jut to keep all the branches up to date ?

**Comment by isaacdorfman** [comment]
> what's the purpose of this merge ? is jut to keep all the branches up to date ?

**Comment by isaacdorfman** [comment]
@HamadiSE @jun-rh 
Yes, we had a discussion with Ryan and decided that this story will be split into multiple task, and the first of them will be to merge this old branch and make sure it still works.

**Comment by isaacdorfman** [comment]
Reopening(I accidentally closed the PR)

**Pull request merged**
