### PR TITLE
add timestamp to log function

### PR DESCRIPTION
**Pull request by hamadise**

### CODE REVIEW

**Comment by hamadise** [comment]
> What does the log header look like now?

```
DEBUG  [Sep 22 15:03:59.816] Issuing get command [oc get csv -n tnf -o json -l test-network-function.com/operator] 
DEBUG  [Sep 22 15:04:01.173] JSON output for all pods labeled with: operator 
DEBUG  [Sep 22 15:04:01.173] Command: /usr/local/bin/oc get csv -n tnf -o json -l test-network-function.com/operator 
DEBUG  [Sep 22 15:04:01.173] {
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "operators.coreos.com/v1alpha1",
            "kind": "ClusterServiceVersion",
            "metadata": {
                "annotations": {
                    "alm-examples": "[\n  {\n    \"apiVersion\": \"cnftest.quay.io/v0\",\n    \"kind\": \"Nginx\",\n    \"metadata\": {\n      \"name\": \"nginx-sample\"\n    },\n 
                    ```

**Comment by hamadise** [comment]
> > > What does the log header look like now?
> > 
> > 
> > ```
> > DEBUG  [Sep 22 15:03:59.816] Issuing get command [oc get csv -n tnf -o json -l test-network-function.com/operator] 
> > DEBUG  [Sep 22 15:04:01.173] JSON output for all pods labeled with: operator 
> > DEBUG  [Sep 22 15:04:01.173] Command: /usr/local/bin/oc get csv -n tnf -o json -l test-network-function.com/operator 
> > DEBUG  [Sep 22 15:04:01.173] {
> >     "apiVersion": "v1",
> >     "items": [
> >         {
> >             "apiVersion": "operators.coreos.com/v1alpha1",
> >             "kind": "ClusterServiceVersion",
> >             "metadata": {
> >                 "annotations": {
> >                     "alm-examples": "[\n  {\n    \"apiVersion\": \"cnftest.quay.io/v0\",\n    \"kind\": \"Nginx\",\n    \"metadata\": {\n      \"name\": \"nginx-sample\"\n    },\n 
> >                     ```
> > ```
> 
> [] around the timestamp seem unnecessary to me. It's fine if they are not easily removable.

I don't think we do control that 
https://yourbasic.org/golang/format-parse-string-time-date-example/ 
all the possible timestamp format that are supported.

**Comment by jun-rh** [comment]
> > > > What does the log header look like now?
> > > 
> > > 
> > > ```
> > > DEBUG  [Sep 22 15:03:59.816] Issuing get command [oc get csv -n tnf -o json -l test-network-function.com/operator] 
> > > DEBUG  [Sep 22 15:04:01.173] JSON output for all pods labeled with: operator 
> > > DEBUG  [Sep 22 15:04:01.173] Command: /usr/local/bin/oc get csv -n tnf -o json -l test-network-function.com/operator 
> > > DEBUG  [Sep 22 15:04:01.173] {
> > >     "apiVersion": "v1",
> > >     "items": [
> > >         {
> > >             "apiVersion": "operators.coreos.com/v1alpha1",
> > >             "kind": "ClusterServiceVersion",
> > >             "metadata": {
> > >                 "annotations": {
> > >                     "alm-examples": "[\n  {\n    \"apiVersion\": \"cnftest.quay.io/v0\",\n    \"kind\": \"Nginx\",\n    \"metadata\": {\n      \"name\": \"nginx-sample\"\n    },\n 
> > >                     ```
> > > ```
> > 
> > 
> > [] around the timestamp seem unnecessary to me. It's fine if they are not easily removable.
> 
> I don't think we do control that
> https://yourbasic.org/golang/format-parse-string-time-date-example/
> all the possible timestamp format that are supported.

I am ok with the time format itself. Just don't like the brackets, wasting space. It's forced by the logrus library then.

**Review by jun-rh — APPROVED** [review]

**Review by edcdavid — APPROVED** [review]

**Comment by hamadise** [comment]
> > > > > What does the log header look like now?
> > > > 
> > > > 
> > > > ```
> > > > DEBUG  [Sep 22 15:03:59.816] Issuing get command [oc get csv -n tnf -o json -l test-network-function.com/operator] 
> > > > DEBUG  [Sep 22 15:04:01.173] JSON output for all pods labeled with: operator 
> > > > DEBUG  [Sep 22 15:04:01.173] Command: /usr/local/bin/oc get csv -n tnf -o json -l test-network-function.com/operator 
> > > > DEBUG  [Sep 22 15:04:01.173] {
> > > >     "apiVersion": "v1",
> > > >     "items": [
> > > >         {
> > > >             "apiVersion": "operators.coreos.com/v1alpha1",
> > > >             "kind": "ClusterServiceVersion",
> > > >             "metadata": {
> > > >                 "annotations": {
> > > >                     "alm-examples": "[\n  {\n    \"apiVersion\": \"cnftest.quay.io/v0\",\n    \"kind\": \"Nginx\",\n    \"metadata\": {\n      \"name\": \"nginx-sample\"\n    },\n 
> > > >                     ```
> > > > ```
> > > 
> > > 
> > > [] around the timestamp seem unnecessary to me. It's fine if they are not easily removable.
> > 
> > 
> > I don't think we do control that
> > https://yourbasic.org/golang/format-parse-string-time-date-example/
> > all the possible timestamp format that are supported.
> 
> I am ok with the time format itself. Just don't like the brackets, wasting space. It's forced by the logrus library then.

@jun-rh  @edcdavid  @greyerof  This is the last format 
```
diagnostic when a cluster is set up and installed with OpenShift 
  diagnostic-cluster-csi-info
  /Users/shamadi/redhat/go/test-network-function/test-network-function/diagnostic/suite.go:110
DEBUG  [Sep 22 21:54:23.726][spawner.go: 236] Utilizing the default buffer size: 32768     
2021/09/22 21:54:23 Sent: "oc get csidriver -o json && echo END_OF_TEST_SENTINEL\n"
2021/09/22 21:54:24 Match for RE: "(?m)(.|\n)+((.|\n)*END_OF_TEST_SENTINEL\n)" found: ["{\n    \"apiVersion\": \"v1\",\n    \"items\": [],\n    \"kind\": \"List\",\n    \"metadata\": {\n        \"resourceVersion\": \"\",\n        \"selfLink\": \"\"\n    }\n}\nEND_OF_TEST_SENTINEL\n" "\n" "END_OF_TEST_SENTINEL\n" ""] Buffer: "{\n    \"apiVersion\": \"v1\",\n    \"items\": [],\n    \"kind\": \"List\",\n    \"metadata\": {\n        \"resourceVersion\": \"\",\n        \"selfLink\": \"\"\n    }\n}\nEND_OF_TEST_SENTINEL\n"
```

**Pull request merged**
