### PR TITLE
Enable diagnostic suite tests in non-OCP environments

### PR DESCRIPTION
**Pull request by javierpena**
Since [1] was merged, we can run the diagnostic suite tests in non-OCP
environments, like minikube. Let's enable them.

[1] - https://github.com/test-network-function/cnf-certification-test-partner/pull/67

### CODE REVIEW

**Comment by javierpena** [comment]
It looks like the container-based versions of minikube lack some utils that are present in the VM-based versions (jq, ifconfig). I'm looking into it.

**Comment by javierpena** [comment]
Keeping the WIP label until https://github.com/test-network-function/cnf-certification-test-partner/pull/72 is merged.

**Comment by javierpena** [comment]
> It shouldn't be all empty?
> 
> ```
>         "Master": {
>           "NodeName": "",
>           "Lscpu": null,
>           "Ifconfig": null,
>           "Lsblk": null,
>           "Lspci": null
>         },
>         "Worker": {
>           "NodeName": "",
>           "Lscpu": null,
>           "Ifconfig": null,
>           "Lsblk": null,
>           "Lspci": null
>         }
>       }```
> ```

This is happening because we first run the diagnostic suite alone, then the rest: https://github.com/test-network-function/test-network-function/blob/main/.github/workflows/pre-main.yaml#L144-L148

I don't see a reason to do that, should we just run all in one go?

**Comment by jun-rh** [comment]
> 

Ah, I see. You are right, let's change this.

**Review by jun-rh — APPROVED** [review]

**Review by greyerof — APPROVED** [review]

**Pull request merged**
