### PR TITLE
Adding operator testing support

### PR DESCRIPTION
**Pull request by edcdavid**
Will remove the forked partner branch used for testing as the last commit

### CODE REVIEW

**Review by HamadiSE — APPROVED** [review]

**Comment by wying3** [comment]
test with 3 nodes cluster, it works

**Review by wying3 — APPROVED** [review]

**Review by edcdavid — COMMENTED** [review]
needs the partner repo side to be merged first

**Review by wying3 — COMMENTED** [review]
David noted this PR need wait for partner repo side to be merged first

**Review by wying3 — CHANGES_REQUESTED** [review]
David noted this PR need wait for partner repo side to be merged first

**Review by jun-rh — APPROVED** [review]

**Review by jun-rh — APPROVED** [review]

**Review by wying3 — APPROVED** [review]

**Pull request merged**
